[project]
name = "codes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.12"
dependencies = [
    "numpy>=2.2.6",
    "psutil>=7.0.0",
    "scipy>=1.15.3",
]
